# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test build and run tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  tests-py2:
    name: Runs tests that require python 2
    runs-on: ubuntu-latest
    container:
      image: python:2.7.18-buster

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Test by decompiling a script and building un.rpyc
      run: |
        ./unrpyc.py --clobber testcases/script.rpyc
        diff -u testcases/script.orig.rpy testcases/script.rpy
        cd un.rpyc;
        # ./compile.py -p 1
        cd ..
